import type { Slide } from '@openmaic/dsl';
import { ElementTypes } from '@openmaic/dsl';

/**
 * 演示幻灯片数据，用于测试 RN 渲染器。
 */
const DEFAULT_THEME = {
  backgroundColor: '#ffffff',
  themeColors: ['#3b82f6', '#22c55e', '#f59e0b', '#ef4444', '#8b5cf6'],
  fontColor: '#333333',
  fontName: 'Inter',
};

export const DEMO_SLIDES: Slide[] = [
  {
    id: 'slide-1',
    viewportSize: 1000,
    viewportRatio: 0.5625,
    theme: DEFAULT_THEME,
    background: { type: 'solid', color: '#ffffff' },
    elements: [
      {
        id: 'el-1',
        type: ElementTypes.TEXT,
        left: 100,
        top: 150,
        width: 800,
        height: 80,
        rotate: 0,
        content: '<h1 style="font-size:36px;font-weight:bold;color:#1e293b;">什么是量子力学？</h1>',
        defaultColor: '#1e293b',
        defaultFontName: 'Inter',
        fill: 'transparent',
      },
      {
        id: 'el-2',
        type: ElementTypes.TEXT,
        left: 100,
        top: 280,
        width: 800,
        height: 120,
        rotate: 0,
        content:
          '<p style="font-size:18px;color:#64748b;line-height:1.6;">量子力学是物理学的一个基础分支，研究微观粒子（如电子、光子、原子）的行为规律。与经典力学不同，量子力学描述的是概率性的世界。</p>',
        defaultColor: '#64748b',
        defaultFontName: 'Inter',
        fill: 'transparent',
      },
      {
        id: 'el-3',
        type: ElementTypes.SHAPE,
        left: 80,
        top: 120,
        width: 8,
        height: 280,
        rotate: 0,
        fill: '#7c3aed',
        path: 'M 4 0 L 4 280',
        viewBox: [8, 280],
        opacity: 1,
        fixedRatio: false,
      },
    ],
  },
  {
    id: 'slide-2',
    viewportSize: 1000,
    viewportRatio: 0.5625,
    theme: DEFAULT_THEME,
    background: { type: 'solid', color: '#ffffff' },
    elements: [
      {
        id: 'el-4',
        type: ElementTypes.TEXT,
        left: 100,
        top: 100,
        width: 800,
        height: 80,
        rotate: 0,
        content: '<h1 style="font-size:36px;font-weight:bold;color:#1e293b;">波粒二象性</h1>',
        defaultColor: '#1e293b',
        defaultFontName: 'Inter',
        fill: 'transparent',
      },
      {
        id: 'el-5',
        type: ElementTypes.TEXT,
        left: 100,
        top: 220,
        width: 800,
        height: 200,
        rotate: 0,
        content:
          '<p style="font-size:18px;color:#64748b;line-height:1.8;">光和物质同时具有波和粒子的双重性质。双缝实验表明，光在未被观测时表现为波，被观测时表现为粒子。</p><br><p style="font-size:16px;color:#7c3aed;font-weight:600;">核心实验：双缝干涉实验</p>',
        defaultColor: '#64748b',
        defaultFontName: 'Inter',
        fill: 'transparent',
      },
    ],
  },
  {
    id: 'slide-3',
    viewportSize: 1000,
    viewportRatio: 0.5625,
    theme: DEFAULT_THEME,
    background: { type: 'solid', color: '#ffffff' },
    elements: [
      {
        id: 'el-6',
        type: ElementTypes.TEXT,
        left: 100,
        top: 100,
        width: 800,
        height: 80,
        rotate: 0,
        content: '<h1 style="font-size:36px;font-weight:bold;color:#1e293b;">不确定性原理</h1>',
        defaultColor: '#1e293b',
        defaultFontName: 'Inter',
        fill: 'transparent',
      },
      {
        id: 'el-7',
        type: ElementTypes.TEXT,
        left: 100,
        top: 220,
        width: 800,
        height: 200,
        rotate: 0,
        content:
          '<p style="font-size:18px;color:#64748b;line-height:1.8;">海森堡不确定性原理：无法同时精确测量粒子的位置和动量。</p><br><p style="font-size:20px;color:#1e293b;font-weight:700;text-align:center;">Δx · Δp ≥ ℏ/2</p>',
        defaultColor: '#64748b',
        defaultFontName: 'Inter',
        fill: 'transparent',
      },
    ],
  },
  {
    id: 'slide-4',
    viewportSize: 1000,
    viewportRatio: 0.5625,
    theme: DEFAULT_THEME,
    background: { type: 'solid', color: '#ffffff' },
    elements: [
      {
        id: 'el-8',
        type: ElementTypes.TEXT,
        left: 100,
        top: 100,
        width: 800,
        height: 80,
        rotate: 0,
        content: '<h1 style="font-size:36px;font-weight:bold;color:#1e293b;">量子叠加态</h1>',
        defaultColor: '#1e293b',
        defaultFontName: 'Inter',
        fill: 'transparent',
      },
      {
        id: 'el-9',
        type: ElementTypes.TEXT,
        left: 100,
        top: 220,
        width: 800,
        height: 200,
        rotate: 0,
        content:
          '<p style="font-size:18px;color:#64748b;line-height:1.8;">叠加态是指量子系统可以同时处于多个状态的线性组合中。</p><br><p style="font-size:20px;color:#1e293b;font-weight:700;text-align:center;">|ψ⟩ = α|0⟩ + β|1⟩</p><br><p style="font-size:14px;color:#94a3b8;text-align:center;">其中 |α|² + |β|² = 1</p>',
        defaultColor: '#64748b',
        defaultFontName: 'Inter',
        fill: 'transparent',
      },
    ],
  },
  {
    id: 'slide-5',
    viewportSize: 1000,
    viewportRatio: 0.5625,
    theme: DEFAULT_THEME,
    background: { type: 'solid', color: '#ffffff' },
    elements: [
      {
        id: 'el-10',
        type: ElementTypes.TEXT,
        left: 100,
        top: 100,
        width: 800,
        height: 80,
        rotate: 0,
        content: '<h1 style="font-size:36px;font-weight:bold;color:#1e293b;">薛定谔的猫</h1>',
        defaultColor: '#1e293b',
        defaultFontName: 'Inter',
        fill: 'transparent',
      },
      {
        id: 'el-11',
        type: ElementTypes.TEXT,
        left: 100,
        top: 220,
        width: 800,
        height: 250,
        rotate: 0,
        content:
          '<p style="font-size:18px;color:#64748b;line-height:1.8;">著名的思想实验：一只猫在盒子里，同时处于"活着"和"死了"的叠加态。只有当盒子被打开（观测）时，叠加态才会坍缩到一个确定的状态。</p>',
        defaultColor: '#64748b',
        defaultFontName: 'Inter',
        fill: 'transparent',
      },
    ],
  },
];
